name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download Tools
      - run: make lint
      - run: make sim
      - run: make gls
      - run: make icestorm_icebreaker_gls

      - run: make clean
